<?php require_once "../src/views/header_nav1.php"?>
    <div class="img-login">
        <p>&nbsp&nbsp&nbsp&nbsp Com o propósito de reunir desenvolvedores e empresas que ainda não estão no mercado digital de forma eficiente, surgiu a MELPRO, que proporciona empresas pequenas a terem seu site de vendas através da escolha do melhor projeto, apresentado por diversos desenvolvedores autônomos. </p>
        <p>&nbsp&nbsp&nbsp&nbsp Pensando em um ambiente colaborativo onde empresas recebem propostas de sites criados por desenvolvedores e fazem sua escolha, o logotipo faz referência a um ambiente de negociação.</p>
        <div class="img-center" ><img  src="../melpro_logotipo.png" alt="logo"/></div>
        <p>&nbsp&nbsp&nbsp&nbsp As novas tecnologias oportunizaram a criação de muitos novos mercados favorecidos principalmente pelos dispositivos mobiles, sites e pelo aumento da velocidade da internet. Ainda, a ascensão de uma cultura colaborativa de consumo estimula uma oferta organizacional menos pautada pela posse e mais preocupada no compartilhamento, troca e empréstimo de produtos e serviços na satisfação das necessidades de consumo.</p>
        <p>&nbsp&nbsp&nbsp&nbsp Diversas empresas são criadas e idealizadas o tempo todo, seja para a venda de um produto específico, um serviço ou atender um segmento de mercado como o varejo, por exemplo. Muitas dificuldades surgem para o pequeno empreendedor no início do seu negócio, tem que pensar em questões como, quais as licenças necessárias para atuar no mercado, em contratação e construção de uma equipe de sucesso, quais sistemas de gestão utilizará e em como fazer um site que atenda suas necessidades para vender de forma online.</p> 
	    <p>&nbsp&nbsp&nbsp&nbsp Neste cenário, o presente trabalho visa o desenvolvimento e apresentação do projeto MELPRO, que proporciona uma plataforma de integração entre os desenvolvedores de sites e as pequenas empresas em um sistema de sucesso compartilhado.</p> 
        <p>&nbsp&nbsp&nbsp&nbsp O site possui o cadastro de desenvolvedores web autônomos e pequenas empresas que desejam construir um site que tenham vendas recorrentes, a proposta será de criar um campo onde as empresas relatam os seus produtos, insiram imagens e façam um resumo de sua história e propósito, logo, uma série de desenvolvedores começam a elaborar um site para tal empresa, de forma que atenda suas necessidades. A empresa escolherá o melhor projeto e aquele que desenvolveu vai subindo em um ranking entre os desenvolvedores que tiveram o projeto aprovado.</p>
	    <p>&nbsp&nbsp&nbsp&nbsp Com o site em funcionamento e as vendas começarem a serem feitas, será descontado um percentual de 5% do valor do produto vendido, a fim de pagar o desenvolvedor e a plataforma da MELPRO, sendo 3% para o desenvolvedor e 2% para a MELPRO. Com isso, ambos podem criar uma receita recorrente em vez de serem pagos uma única vez pelo projeto, e a empresa consegue ter o seu site publicado sem nenhum custo inicial.</p>
    </div>
<?php require_once "../src/views/footer.php" ?>